//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Displays&quot;: [
        ///    {
        ///      &quot;Uid&quot;: &quot;b9bb34dd-159e-47ad-9ec6-2fdd9b3953c1&quot;,
        ///      &quot;ScreenName&quot;: &quot;\\\\.\\DISPLAY3&quot;,
        ///      &quot;IsMain&quot;: true,
        ///      &quot;Dashboards&quot;: [
        ///        {
        ///          &quot;Uid&quot;: &quot;c71c0d44-97f5-47a1-b22f-9ed027421c58&quot;,
        ///          &quot;Name&quot;: &quot;op&quot;,
        ///          &quot;IsRemoveable&quot;: true,
        ///          &quot;DashboardType&quot;: &quot;Operational&quot;,
        ///          &quot;IconName&quot;: &quot;OpenedMap&quot;,
        ///          &quot;Layout&quot;: {
        ///            &quot;$type&quot;: &quot;Magal.FortisX.Client.Model.Store.DockLayout, Magal.FortisX.Client&quot;,
        ///            &quot;GridColumns&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newState {
            get {
                return ResourceManager.GetString("newState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Displays&quot;: [
        ///    {
        ///      &quot;Uid&quot;: &quot;b9bb34dd-159e-47ad-9ec6-2fdd9b3953c1&quot;,
        ///      &quot;ScreenName&quot;: &quot;\\\\.\\DISPLAY3&quot;,
        ///      &quot;IsMain&quot;: true,
        ///      &quot;Dashboards&quot;: [
        ///        {
        ///          &quot;Uid&quot;: &quot;c71c0d44-97f5-47a1-b22f-9ed027421c58&quot;,
        ///          &quot;Name&quot;: &quot;op&quot;,
        ///          &quot;IsRemoveable&quot;: true,
        ///          &quot;DashboardType&quot;: &quot;Operational&quot;,
        ///          &quot;IconName&quot;: &quot;OpenedMap&quot;,
        ///          &quot;Layout&quot;: {
        ///            &quot;$type&quot;: &quot;Magal.FortisX.Client.Model.Store.DockLayout, Magal.FortisX.Client&quot;,
        ///            &quot;GridColumns&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oldState {
            get {
                return ResourceManager.GetString("oldState", resourceCulture);
            }
        }
    }
}
